import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const wordmark = localFont({
  src: "../fonts/display/Autolova.woff2",
  variable: "--font-wordmark",
  preload: false
});

const display = localFont({
  src: [
    {
      path: "../fonts/display/Classica-Book.woff2",
      weight: "400",
    },
    {
      path: "../fonts/display/Classica-Bold.woff2",
      weight: "700",
    },
  ],
  variable: "--font-display",
  preload: true
});

const body = localFont({
  src: [
    {
      path: "../fonts/body/hanken_grotesk/HankenGrotesk-Regular.woff2",
      weight: "400",
    },
    {
      path: "../fonts/body/hanken_grotesk/HankenGrotesk-SemiBold.woff2",
      weight: "700",
    },
    {
      path: "../fonts/body/hanken_grotesk/HankenGrotesk-Bold.woff2",
      weight: "900",
    },
  ],
  variable: "--font-body",
  preload: true
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${wordmark.variable} ${display.variable} ${body.variable} min-h-screen font-body antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
